// Expo SDK 57's iOS template still uses the pre-iOS-13 AppDelegate-only
// lifecycle (creates its UIWindow directly in didFinishLaunching). Starting
// with the iOS 27 SDK, Apple made UIScene adoption mandatory: an app without
// a scene delegate now crashes on launch with "UIScene life cycle is
// required for apps built with this SDK." Expo fixed this upstream in SDK 58
// (ExpoAppSceneDelegate), but this project is pinned to SDK 57. This plugin
// backports the minimal equivalent so `expo prebuild` keeps producing a
// working iOS 27 build. Remove this plugin once the project upgrades to a
// stable Expo SDK that ships the fix natively.
const { withAppDelegate, withInfoPlist, withXcodeProject, withDangerousMod, IOSConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SCENE_DELEGATE_CLASS_NAME = 'SceneDelegate';

const SCENE_DELEGATE_SOURCE = `// Generated by plugins/withIOSSceneDelegate.js — do not edit by hand.
import UIKit
import React

@objc(SceneDelegate)
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
    guard let windowScene = scene as? UIWindowScene,
      let appDelegate = UIApplication.shared.delegate as? AppDelegate,
      let factory = appDelegate.reactNativeFactory
    else {
      return
    }

    let window = UIWindow(windowScene: windowScene)
    appDelegate.window = window
    self.window = window
    factory.startReactNative(withModuleName: "main", in: window, launchOptions: nil)

    if let url = connectionOptions.urlContexts.first?.url {
      RCTLinkingManager.application(UIApplication.shared, open: url, options: [:])
    } else if let userActivity = connectionOptions.userActivities.first {
      RCTLinkingManager.application(UIApplication.shared, continue: userActivity) { _ in }
    }
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    guard let url = URLContexts.first?.url else { return }
    RCTLinkingManager.application(UIApplication.shared, open: url, options: [:])
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    RCTLinkingManager.application(UIApplication.shared, continue: userActivity) { _ in }
  }
}
`;

function withSceneDelegateFile(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const iosRoot = config.modRequest.platformProjectRoot;
      const projectName = config.modRequest.projectName;
      const targetDir = path.join(iosRoot, projectName);
      fs.writeFileSync(path.join(targetDir, `${SCENE_DELEGATE_CLASS_NAME}.swift`), SCENE_DELEGATE_SOURCE);
      return config;
    },
  ]);
}

function withSceneDelegateXcodeProject(config) {
  return withXcodeProject(config, (config) => {
    const project = config.modResults;
    const projectName = config.modRequest.projectName;
    IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
      filepath: `${projectName}/${SCENE_DELEGATE_CLASS_NAME}.swift`,
      groupName: projectName,
      project,
    });
    return config;
  });
}

function withSceneManifest(config) {
  return withInfoPlist(config, (config) => {
    config.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: `$(PRODUCT_MODULE_NAME).${SCENE_DELEGATE_CLASS_NAME}`,
          },
        ],
      },
    };
    return config;
  });
}

function withAppDelegateNoWindow(config) {
  return withAppDelegate(config, (config) => {
    const contents = config.modResults.contents;

    const windowCreationBlock =
      /#if os\(iOS\) \|\| os\(tvOS\)\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\n\s*factory\.startReactNative\(\n\s*withModuleName: "main",\n\s*in: window,\n\s*launchOptions: launchOptions\)\n#endif\n/;

    if (!windowCreationBlock.test(contents)) {
      throw new Error(
        'withIOSSceneDelegate: could not find the expected window-creation block in AppDelegate.swift. ' +
          'The Expo template likely changed — update plugins/withIOSSceneDelegate.js to match.'
      );
    }

    config.modResults.contents = contents.replace(
      windowCreationBlock,
      '    // Window creation and React Native startup happen in SceneDelegate.swift,\n' +
        '    // which iOS 27 requires apps to adopt (see plugins/withIOSSceneDelegate.js).\n'
    );

    return config;
  });
}

module.exports = function withIOSSceneDelegate(config) {
  config = withSceneDelegateFile(config);
  config = withSceneDelegateXcodeProject(config);
  config = withSceneManifest(config);
  config = withAppDelegateNoWindow(config);
  return config;
};
